# Generated by Django 4.2.15 on 2025-01-10 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ElementaryEnrollment", "0005_alter_enrollmentperiod_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="schedule",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="academic_year",
            field=models.CharField(
                default="2022-2024", help_text="Format: YYYY-YYYY", max_length=9
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enrollment",
            name="enrollment_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enrollment",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="academic_year",
            field=models.CharField(
                default="", help_text="Format: YYYY-YYYY", max_length=9
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="section",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="ElementaryEnrollment.section",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="section",
            name="academic_year",
            field=models.CharField(
                default="", help_text="Format: YYYY-YYYY", max_length=9
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="section",
            name="adviser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="current_students",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="section",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="section",
            name="max_students",
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name="student",
            name="academic_year",
            field=models.CharField(
                default="", help_text="Format: YYYY-YYYY", max_length=9
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="semester",
            field=models.CharField(
                choices=[
                    ("First", "First Semester"),
                    ("Second", "Second Semester"),
                    ("Summer", "Summer"),
                ],
                default="First",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="code",
            field=models.CharField(default="", max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="grade_level",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="units",
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
        migrations.AlterUniqueTogether(
            name="schedule",
            unique_together={("section", "academic_year")},
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("grade_level", "section", "academic_year")},
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="fri_7",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="grade_level",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="mon_7",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="schedule_section",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="student",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="thu_7",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="time_slot",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="tue_7",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="wed_7",
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MON", "Monday"),
                            ("TUE", "Tuesday"),
                            ("WED", "Wednesday"),
                            ("THU", "Thursday"),
                            ("FRI", "Friday"),
                        ],
                        max_length=3,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="ElementaryEnrollment.schedule",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ElementaryEnrollment.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["day", "start_time"],
                "unique_together": {("schedule", "day", "start_time")},
            },
        ),
    ]
