# Generated by Django 4.2.15 on 2025-01-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ElementaryEnrollment",
            "0006_remove_subject_schedule_enrollment_academic_year_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="current_students",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
